| 2024:06:13 16:08:38,767 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\main.py modified; restarting server
| 2024:06:13 16:08:39,170 | I | root | ------
| 2024:06:13 16:08:39,219 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:08:39,418 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:08:39,422 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:10:29,533 | I | root | web\branchManager\dashboard.py 73 get 	
| 2024:06:13 16:10:29,535 | D | root | web\branchManager\dashboard.py 154 get RSP	{'code': 4001, 'status': False, 'message': 'Invalid - [ Authorization ]', 'result': []}
| 2024:06:13 16:10:29,539 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 21.04ms
| 2024:06:13 16:10:35,003 | W | root | web\branchManager\dashboard.py 145 get EXC	Exception: TypeError. Argument: ("object AsyncIOMotorCursor can't be used in 'await' expression",)
| 2024:06:13 16:10:35,006 | D | root | web\branchManager\dashboard.py 146 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 91 TYPE: <class 'TypeError'>
| 2024:06:13 16:10:35,008 | D | root | web\branchManager\dashboard.py 154 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:10:35,009 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 9.72ms
| 2024:06:13 16:11:25,445 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:11:25,850 | I | root | ------
| 2024:06:13 16:11:25,884 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:11:26,042 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:11:26,047 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:11:28,156 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666accd5f08a7a456a20894c, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666accd5f08a7a456a20894c"}}
| 2024:06:13 16:11:28,157 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666accd5f08a7a456a20894c, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666accd5f08a7a456a20894c"}, "remainingTimeMS": 30}
| 2024:06:13 16:11:28,158 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666accd5f08a7a456a20894c, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666accd5f08a7a456a20894c"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:11:28,159 | D | pymongo.command | {"clientId": {"$oid": "666accd5f08a7a456a20894c"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666accd8f08a7a456a20894d\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"HsAGivcxSSa4uXRjUY1QLQ==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 50, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:11:28,161 | D | pymongo.command | {"clientId": {"$oid": "666accd5f08a7a456a20894c"}, "message": "Command succeeded", "durationMS": 1.286, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 50, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:11:28,173 | W | root | web\branchManager\dashboard.py 145 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:11:28,174 | D | root | web\branchManager\dashboard.py 146 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 97 TYPE: <class 'IndexError'>
| 2024:06:13 16:11:28,175 | D | root | web\branchManager\dashboard.py 154 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:11:28,176 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 21.33ms
| 2024:06:13 16:12:02,571 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:12:02,950 | I | root | ------
| 2024:06:13 16:12:03,064 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:12:03,265 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:12:03,269 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:12:04,330 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666accfa7b0bea91e778751b, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666accfa7b0bea91e778751b"}}
| 2024:06:13 16:12:04,331 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666accfa7b0bea91e778751b, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666accfa7b0bea91e778751b"}, "remainingTimeMS": 29}
| 2024:06:13 16:12:04,336 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666accfa7b0bea91e778751b, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666accfa7b0bea91e778751b"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:12:04,339 | D | pymongo.command | {"clientId": {"$oid": "666accfa7b0bea91e778751b"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666accfc7b0bea91e778751c\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"OYFemmtZSByHBilAZHpxsg==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 54, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:12:04,341 | D | pymongo.command | {"clientId": {"$oid": "666accfa7b0bea91e778751b"}, "message": "Command succeeded", "durationMS": 2.059, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 54, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:12:04,343 | I | STDOUT | ****************** []
| 2024:06:13 16:12:04,358 | W | root | web\branchManager\dashboard.py 146 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:12:04,359 | D | root | web\branchManager\dashboard.py 147 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 98 TYPE: <class 'IndexError'>
| 2024:06:13 16:12:04,361 | D | root | web\branchManager\dashboard.py 155 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:12:04,362 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 36.35ms
| 2024:06:13 16:12:36,293 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:12:36,724 | I | root | ------
| 2024:06:13 16:12:36,781 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:12:36,937 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:12:36,942 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:12:38,151 | I | STDOUT | None
| 2024:06:13 16:12:38,153 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd1c28c7338e8128468f, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd1c28c7338e8128468f"}}
| 2024:06:13 16:12:38,154 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd1c28c7338e8128468f, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd1c28c7338e8128468f"}, "remainingTimeMS": 30}
| 2024:06:13 16:12:38,155 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd1c28c7338e8128468f, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acd1c28c7338e8128468f"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:12:38,157 | D | pymongo.command | {"clientId": {"$oid": "666acd1c28c7338e8128468f"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acd1e28c7338e81284690\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"M0PcvKlVRgOdodbIQwnLHQ==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 56, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:12:38,158 | D | pymongo.command | {"clientId": {"$oid": "666acd1c28c7338e8128468f"}, "message": "Command succeeded", "durationMS": 0.558, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 56, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:12:38,159 | I | STDOUT | ****************** []
| 2024:06:13 16:12:38,168 | W | root | web\branchManager\dashboard.py 147 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:12:38,168 | D | root | web\branchManager\dashboard.py 148 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 99 TYPE: <class 'IndexError'>
| 2024:06:13 16:12:38,169 | D | root | web\branchManager\dashboard.py 156 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:12:38,170 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 19.29ms
| 2024:06:13 16:13:28,968 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:13:29,332 | I | root | ------
| 2024:06:13 16:13:29,367 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:13:29,515 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:13:29,520 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:13:36,501 | I | STDOUT | ****************** None
| 2024:06:13 16:13:36,503 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd510cc423c673446608, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd510cc423c673446608"}}
| 2024:06:13 16:13:36,504 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd510cc423c673446608, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd510cc423c673446608"}, "remainingTimeMS": 30}
| 2024:06:13 16:13:36,504 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd510cc423c673446608, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acd510cc423c673446608"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:13:36,506 | D | pymongo.command | {"clientId": {"$oid": "666acd510cc423c673446608"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acd580cc423c673446609\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"9mgBPxj3R1S+J1RUuMCXLA==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 60, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:13:36,508 | D | pymongo.command | {"clientId": {"$oid": "666acd510cc423c673446608"}, "message": "Command succeeded", "durationMS": 1.544, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 60, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:13:36,508 | I | STDOUT | ****************** []
| 2024:06:13 16:13:36,519 | W | root | web\branchManager\dashboard.py 147 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:13:36,520 | D | root | web\branchManager\dashboard.py 148 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 99 TYPE: <class 'IndexError'>
| 2024:06:13 16:13:36,521 | D | root | web\branchManager\dashboard.py 156 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:13:36,522 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 22.08ms
| 2024:06:13 16:14:01,543 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:14:01,961 | I | root | ------
| 2024:06:13 16:14:01,993 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:14:02,158 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:14:02,161 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:14:03,166 | I | STDOUT | ****************** None
| 2024:06:13 16:14:03,170 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd712940bebdf90ee611, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd712940bebdf90ee611"}}
| 2024:06:13 16:14:03,170 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd712940bebdf90ee611, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd712940bebdf90ee611"}, "remainingTimeMS": 30}
| 2024:06:13 16:14:03,196 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd712940bebdf90ee611, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acd712940bebdf90ee611"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:03,210 | D | pymongo.command | {"clientId": {"$oid": "666acd712940bebdf90ee611"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acd732940bebdf90ee612\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"FgcSM3zOS7iKnS+nqZ0U6Q==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 63, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:03,211 | D | pymongo.command | {"clientId": {"$oid": "666acd712940bebdf90ee611"}, "message": "Command succeeded", "durationMS": 1.0150000000000001, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 63, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:03,213 | I | STDOUT | ****************** []
| 2024:06:13 16:14:03,225 | W | root | web\branchManager\dashboard.py 147 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:14:03,228 | D | root | web\branchManager\dashboard.py 148 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 99 TYPE: <class 'IndexError'>
| 2024:06:13 16:14:03,229 | D | root | web\branchManager\dashboard.py 156 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:14:03,230 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 63.85ms
| 2024:06:13 16:14:12,677 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:14:13,043 | I | root | ------
| 2024:06:13 16:14:13,078 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:14:13,231 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:14:13,234 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:14:20,511 | I | STDOUT | ****************** None
| 2024:06:13 16:14:20,513 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd7d9b348ca113732fa6, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd7d9b348ca113732fa6"}}
| 2024:06:13 16:14:20,514 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd7d9b348ca113732fa6, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd7d9b348ca113732fa6"}, "remainingTimeMS": 30}
| 2024:06:13 16:14:20,515 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd7d9b348ca113732fa6, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acd7d9b348ca113732fa6"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:20,517 | D | pymongo.command | {"clientId": {"$oid": "666acd7d9b348ca113732fa6"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acd849b348ca113732fa7\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"G0yoBvO9THqNJWJJVuJZ/w==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 66, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:20,517 | D | pymongo.command | {"clientId": {"$oid": "666acd7d9b348ca113732fa6"}, "message": "Command succeeded", "durationMS": 0.505, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 66, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:20,529 | W | root | web\branchManager\dashboard.py 147 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:14:20,531 | D | root | web\branchManager\dashboard.py 148 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 99 TYPE: <class 'IndexError'>
| 2024:06:13 16:14:20,532 | D | root | web\branchManager\dashboard.py 156 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:14:20,533 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 23.35ms
| 2024:06:13 16:14:46,751 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:14:47,151 | I | root | ------
| 2024:06:13 16:14:47,187 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:14:47,343 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:14:47,347 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:14:51,066 | I | STDOUT | ****************** None
| 2024:06:13 16:14:51,068 | I | STDOUT | ****************** branchManager
| 2024:06:13 16:14:51,068 | I | STDOUT | ****************** 66681a63ed55f1052413d85c
| 2024:06:13 16:14:51,069 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd9f738f90a659a53435, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd9f738f90a659a53435"}}
| 2024:06:13 16:14:51,070 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd9f738f90a659a53435, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acd9f738f90a659a53435"}, "remainingTimeMS": 30}
| 2024:06:13 16:14:51,070 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acd9f738f90a659a53435, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acd9f738f90a659a53435"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:51,072 | D | pymongo.command | {"clientId": {"$oid": "666acd9f738f90a659a53435"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acda3738f90a659a53436\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"z5zaIxLCTzuz0rEs1xVHfw==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 69, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:51,073 | D | pymongo.command | {"clientId": {"$oid": "666acd9f738f90a659a53435"}, "message": "Command succeeded", "durationMS": 1.0, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 69, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:14:51,084 | W | root | web\branchManager\dashboard.py 149 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:14:51,086 | D | root | web\branchManager\dashboard.py 150 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 101 TYPE: <class 'IndexError'>
| 2024:06:13 16:14:51,087 | D | root | web\branchManager\dashboard.py 158 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:14:51,087 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 20.62ms
| 2024:06:13 16:15:35,870 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:15:36,235 | I | root | ------
| 2024:06:13 16:15:36,271 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:15:36,432 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:15:36,435 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:15:37,205 | I | STDOUT | **************** {'userId': '6668259eb27f0e68666fa3ba', 'companyId': '66681a63ed55f1052413d85c', 'userRole': 'branchManager'}
| 2024:06:13 16:15:37,205 | I | STDOUT | ****************** None
| 2024:06:13 16:15:37,206 | I | STDOUT | ****************** branchManager
| 2024:06:13 16:15:37,206 | I | STDOUT | ****************** 66681a63ed55f1052413d85c
| 2024:06:13 16:15:37,209 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acdd020c2df135d946939, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acdd020c2df135d946939"}}
| 2024:06:13 16:15:37,210 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acdd020c2df135d946939, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acdd020c2df135d946939"}, "remainingTimeMS": 30}
| 2024:06:13 16:15:37,211 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acdd020c2df135d946939, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acdd020c2df135d946939"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:15:37,213 | D | pymongo.command | {"clientId": {"$oid": "666acdd020c2df135d946939"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acdd120c2df135d94693a\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"pp/yYPQVRPaqrGrI5WLsyw==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 71, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:15:37,215 | D | pymongo.command | {"clientId": {"$oid": "666acdd020c2df135d946939"}, "message": "Command succeeded", "durationMS": 2.09, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 71, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:15:37,236 | W | root | web\branchManager\dashboard.py 150 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:15:37,238 | D | root | web\branchManager\dashboard.py 151 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 102 TYPE: <class 'IndexError'>
| 2024:06:13 16:15:37,240 | D | root | web\branchManager\dashboard.py 159 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:15:37,241 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 37.90ms
| 2024:06:13 16:15:55,453 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:15:55,847 | I | root | ------
| 2024:06:13 16:15:55,891 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:15:56,076 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:15:56,079 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:16:02,350 | I | STDOUT | **************** {'userId': '6668259eb27f0e68666fa3ba', 'companyId': '66681a63ed55f1052413d85c', 'userRole': 'branchManager'}
| 2024:06:13 16:16:02,350 | I | STDOUT | ****************** None
| 2024:06:13 16:16:02,350 | I | STDOUT | ****************** branchManager
| 2024:06:13 16:16:02,350 | I | STDOUT | ****************** 66681a63ed55f1052413d85c
| 2024:06:13 16:16:02,353 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acde3d7bd2b80ae6af099, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acde3d7bd2b80ae6af099"}}
| 2024:06:13 16:16:02,353 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acde3d7bd2b80ae6af099, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acde3d7bd2b80ae6af099"}, "remainingTimeMS": 30}
| 2024:06:13 16:16:02,354 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acde3d7bd2b80ae6af099, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acde3d7bd2b80ae6af099"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:02,356 | D | pymongo.command | {"clientId": {"$oid": "666acde3d7bd2b80ae6af099"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acdead7bd2b80ae6af09a\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"pVylU4H4SOS5nx4hf8XgPw==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 75, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:02,357 | D | pymongo.command | {"clientId": {"$oid": "666acde3d7bd2b80ae6af099"}, "message": "Command succeeded", "durationMS": 1.0070000000000001, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 75, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:02,369 | W | root | web\branchManager\dashboard.py 150 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:16:02,370 | D | root | web\branchManager\dashboard.py 151 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 102 TYPE: <class 'IndexError'>
| 2024:06:13 16:16:02,373 | D | root | web\branchManager\dashboard.py 159 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:16:02,373 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 23.44ms
| 2024:06:13 16:16:17,599 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:16:17,998 | I | root | ------
| 2024:06:13 16:16:18,036 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:16:18,211 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:16:18,215 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:16:19,472 | I | STDOUT | **************** Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY4MjU5ZWIyN2YwZTY4NjY2ZmEzYmEiLCJjb21wYW55SWQiOiI2NjY4MWE2M2VkNTVmMTA1MjQxM2Q4NWMiLCJ1c2VyUm9sZSI6ImJyYW5jaE1hbmFnZXIifQ.jWH6CX9L0am9vxdejg4gRcRuMmAzrUi9asxi1L2lgDI
| 2024:06:13 16:16:19,472 | I | STDOUT | **************** {'userId': '6668259eb27f0e68666fa3ba', 'companyId': '66681a63ed55f1052413d85c', 'userRole': 'branchManager'}
| 2024:06:13 16:16:19,473 | I | STDOUT | ****************** None
| 2024:06:13 16:16:19,473 | I | STDOUT | ****************** branchManager
| 2024:06:13 16:16:19,473 | I | STDOUT | ****************** 66681a63ed55f1052413d85c
| 2024:06:13 16:16:19,475 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acdf9b9449d3afd2d4fcd, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acdf9b9449d3afd2d4fcd"}}
| 2024:06:13 16:16:19,475 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acdf9b9449d3afd2d4fcd, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666acdf9b9449d3afd2d4fcd"}, "remainingTimeMS": 30}
| 2024:06:13 16:16:19,476 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666acdf9b9449d3afd2d4fcd, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666acdf9b9449d3afd2d4fcd"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:19,495 | D | pymongo.command | {"clientId": {"$oid": "666acdf9b9449d3afd2d4fcd"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"666acdfbb9449d3afd2d4fce\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"z/FyqWoCS/SxfkTW9L7aQg==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 77, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:19,496 | D | pymongo.command | {"clientId": {"$oid": "666acdf9b9449d3afd2d4fcd"}, "message": "Command succeeded", "durationMS": 0.9890000000000001, "reply": "{\"cursor\": {\"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 77, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:19,509 | W | root | web\branchManager\dashboard.py 151 get EXC	Exception: IndexError. Argument: ('list index out of range',)
| 2024:06:13 16:16:19,511 | D | root | web\branchManager\dashboard.py 152 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 103 TYPE: <class 'IndexError'>
| 2024:06:13 16:16:19,512 | D | root | web\branchManager\dashboard.py 160 get RSP	{'code': 5010, 'status': False, 'message': 'Internal Error, Please Contact the Support Team.', 'result': []}
| 2024:06:13 16:16:19,513 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 41.44ms
| 2024:06:13 16:16:54,739 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:16:55,138 | I | root | ------
| 2024:06:13 16:16:55,180 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:16:55,365 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:16:55,369 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:16:59,128 | I | STDOUT | **************** {'userId': '6668259eb27f0e68666fa3ba', 'companyId': '66681a63ed55f1052413d85c', 'userRole': 'branchManager'}
| 2024:06:13 16:16:59,129 | I | STDOUT | ****************** 6668259eb27f0e68666fa3ba
| 2024:06:13 16:16:59,129 | I | STDOUT | ****************** branchManager
| 2024:06:13 16:16:59,129 | I | STDOUT | ****************** 66681a63ed55f1052413d85c
| 2024:06:13 16:16:59,131 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666ace1fedbded277e31217f, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666ace1fedbded277e31217f"}}
| 2024:06:13 16:16:59,132 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666ace1fedbded277e31217f, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666ace1fedbded277e31217f"}, "remainingTimeMS": 30}
| 2024:06:13 16:16:59,133 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666ace1fedbded277e31217f, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666ace1fedbded277e31217f"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:59,152 | D | pymongo.command | {"clientId": {"$oid": "666ace1fedbded277e31217f"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"6668259eb27f0e68666fa3ba\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"v2lBr3Z/RLmaAnYzG50S0g==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 81, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:59,153 | D | pymongo.command | {"clientId": {"$oid": "666ace1fedbded277e31217f"}, "message": "Command succeeded", "durationMS": 1.8920000000000001, "reply": "{\"cursor\": {\"firstBatch\": [{\"_id\": {\"$oid\": \"6668259eb27f0e68666fa3ba\"}, \"companyId\": {\"$oid\": \"66681a63ed55f1052413d85c\"}, \"branchId\": {\"$oid\": \"66681d79a3c4ba4888ad4965\"}, \"email\": \"johndoe@gmail.com\", \"password\": {\"$binary\": {\"base64\": \"Z0FBQUFBQm1hQ1dlc0Vfd1RXNDdpZHFLVkRzTzJZTHVBaHpma1hTQXpaVGVqdW9XNXQxelVPbm02eS1NQW1uSjRNOUItM0FHeDBmdXFpd2ozUGZ6d1FnU2h2Y1RiUS1rN0E9PQ==\", \"subType\": \"00\"}}, \"role\": {\"$oid\": \"666824e2c43f23878e12216c\"}, \"active\": true, \"createdAt\": 1718101406408103, \"createdBy\": {\"$oid\": \"6668259eb27f0e68666fa3b9\"}, \"personalInfo\": {\"firstName\": \"John\", \"lastName\": \"Doe\", \"phone\": \"1234567890\"}}], \"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 81, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:16:59,154 | I | STDOUT | {'totalEmployees': AsyncIOMotorLatentCommandCursor(<motor.core._LatentCursor object at 0x000001A104521290>), 'totalHRs': 0, 'totalClients': 0, 'deliveredProjects': 0, 'pendingProjects': 0, 'totalProjects': 0}
| 2024:06:13 16:16:59,167 | D | root | web\branchManager\dashboard.py 159 get RSP	{'code': 4100, 'status': False, 'message': '', 'result': {'totalEmployees': AsyncIOMotorLatentCommandCursor(<motor.core._LatentCursor object at 0x000001A104521290>), 'totalHRs': 0, 'totalClients': 0, 'deliveredProjects': 0, 'pendingProjects': 0, 'totalProjects': 0}}
| 2024:06:13 16:16:59,169 | W | root | web\branchManager\dashboard.py 172 get EXC	Exception: TypeError. Argument: ('Object of type AsyncIOMotorLatentCommandCursor is not JSON serializable',)
| 2024:06:13 16:16:59,170 | D | root | web\branchManager\dashboard.py 173 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 161 TYPE: <class 'TypeError'>
| 2024:06:13 16:16:59,171 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 43.60ms
| 2024:06:13 16:17:37,389 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:17:37,832 | I | root | ------
| 2024:06:13 16:17:37,868 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:17:38,048 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:17:38,051 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:17:40,930 | I | STDOUT | **************** {'userId': '6668259eb27f0e68666fa3ba', 'companyId': '66681a63ed55f1052413d85c', 'userRole': 'branchManager'}
| 2024:06:13 16:17:40,932 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666ace49004393bdcdc7c0bd, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666ace49004393bdcdc7c0bd"}}
| 2024:06:13 16:17:40,933 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666ace49004393bdcdc7c0bd, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666ace49004393bdcdc7c0bd"}, "remainingTimeMS": 30}
| 2024:06:13 16:17:40,933 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666ace49004393bdcdc7c0bd, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.0>]>", "clientId": {"$oid": "666ace49004393bdcdc7c0bd"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:17:40,958 | D | pymongo.command | {"clientId": {"$oid": "666ace49004393bdcdc7c0bd"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"6668259eb27f0e68666fa3ba\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"YiG2f43hS12CJkz6Bm3UjA==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 84, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:17:40,988 | D | pymongo.command | {"clientId": {"$oid": "666ace49004393bdcdc7c0bd"}, "message": "Command succeeded", "durationMS": 30.341, "reply": "{\"cursor\": {\"firstBatch\": [{\"_id\": {\"$oid\": \"6668259eb27f0e68666fa3ba\"}, \"companyId\": {\"$oid\": \"66681a63ed55f1052413d85c\"}, \"branchId\": {\"$oid\": \"66681d79a3c4ba4888ad4965\"}, \"email\": \"johndoe@gmail.com\", \"password\": {\"$binary\": {\"base64\": \"Z0FBQUFBQm1hQ1dlc0Vfd1RXNDdpZHFLVkRzTzJZTHVBaHpma1hTQXpaVGVqdW9XNXQxelVPbm02eS1NQW1uSjRNOUItM0FHeDBmdXFpd2ozUGZ6d1FnU2h2Y1RiUS1rN0E9PQ==\", \"subType\": \"00\"}}, \"role\": {\"$oid\": \"666824e2c43f23878e12216c\"}, \"active\": true, \"createdAt\": 1718101406408103, \"createdBy\": {\"$oid\": \"6668259eb27f0e68666fa3b9\"}, \"personalInfo\": {\"firstName\": \"John\", \"lastName\": \"Doe\", \"phone\": \"1234567890\"}}], \"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 84, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:17:40,998 | I | STDOUT | {'totalEmployees': AsyncIOMotorLatentCommandCursor(<motor.core._LatentCursor object at 0x000001DE05C211D0>), 'totalHRs': 0, 'totalClients': 0, 'deliveredProjects': 0, 'pendingProjects': 0, 'totalProjects': 0}
| 2024:06:13 16:17:41,030 | D | root | web\branchManager\dashboard.py 156 get RSP	{'code': 4100, 'status': False, 'message': '', 'result': {'totalEmployees': AsyncIOMotorLatentCommandCursor(<motor.core._LatentCursor object at 0x000001DE05C211D0>), 'totalHRs': 0, 'totalClients': 0, 'deliveredProjects': 0, 'pendingProjects': 0, 'totalProjects': 0}}
| 2024:06:13 16:17:41,037 | W | root | web\branchManager\dashboard.py 169 get EXC	Exception: TypeError. Argument: ('Object of type AsyncIOMotorLatentCommandCursor is not JSON serializable',)
| 2024:06:13 16:17:41,041 | D | root | web\branchManager\dashboard.py 170 get EX2	FILE: C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py LINE: 158 TYPE: <class 'TypeError'>
| 2024:06:13 16:17:41,042 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 113.45ms
| 2024:06:13 16:19:57,569 | I | tornado.general | C:\Users\asabi\OneDrive\Desktop\officeManagement\server\web\branchManager\dashboard.py modified; restarting server
| 2024:06:13 16:19:57,971 | I | root | ------
| 2024:06:13 16:19:58,029 | I | root | <frozen importlib._bootstrap> 241 _call_with_frames_removed All Logs written in ./log/run.log
| 2024:06:13 16:19:58,184 | D | asyncio | Using proactor: IocpProactor
| 2024:06:13 16:19:58,190 | I | root | main.py 67 __init__ APP	Running Tornado Application Port - [ 5166 ]
| 2024:06:13 16:20:02,736 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666aced542533387f04e44dd, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666aced542533387f04e44dd"}}
| 2024:06:13 16:20:02,736 | D | pymongo.serverSelection | {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666aced542533387f04e44dd, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "666aced542533387f04e44dd"}, "remainingTimeMS": 30}
| 2024:06:13 16:20:02,737 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 666aced542533387f04e44dd, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.01600000000325963>]>", "clientId": {"$oid": "666aced542533387f04e44dd"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:20:02,740 | D | pymongo.command | {"clientId": {"$oid": "666aced542533387f04e44dd"}, "message": "Command started", "command": "{\"find\": \"user\", \"filter\": {\"_id\": {\"$oid\": \"6668259eb27f0e68666fa3ba\"}}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"wmpGIt1nQ8itVFU2U1NolA==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 87, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:20:02,741 | D | pymongo.command | {"clientId": {"$oid": "666aced542533387f04e44dd"}, "message": "Command succeeded", "durationMS": 1.002, "reply": "{\"cursor\": {\"firstBatch\": [{\"_id\": {\"$oid\": \"6668259eb27f0e68666fa3ba\"}, \"companyId\": {\"$oid\": \"66681a63ed55f1052413d85c\"}, \"branchId\": {\"$oid\": \"66681d79a3c4ba4888ad4965\"}, \"email\": \"johndoe@gmail.com\", \"password\": {\"$binary\": {\"base64\": \"Z0FBQUFBQm1hQ1dlc0Vfd1RXNDdpZHFLVkRzTzJZTHVBaHpma1hTQXpaVGVqdW9XNXQxelVPbm02eS1NQW1uSjRNOUItM0FHeDBmdXFpd2ozUGZ6d1FnU2h2Y1RiUS1rN0E9PQ==\", \"subType\": \"00\"}}, \"role\": {\"$oid\": \"666824e2c43f23878e12216c\"}, \"active\": true, \"createdAt\": 1718101406408103, \"createdBy\": {\"$oid\": \"6668259eb27f0e68666fa3b9\"}, \"personalInfo\": {\"firstName\": \"John\", \"lastName\": \"Doe\", \"phone\": \"1234567890\"}}], \"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "find", "databaseName": "OfficeDataBase", "requestId": 18467, "operationId": 18467, "driverConnectionId": 1, "serverConnectionId": 87, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:20:02,742 | D | pymongo.serverSelection | {"message": "Server selection started", "selector": "Primary()", "operation": "aggregate", "topologyDescription": "<TopologyDescription id: 666aced542533387f04e44dd, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.01600000000325963>]>", "clientId": {"$oid": "666aced542533387f04e44dd"}}
| 2024:06:13 16:20:02,742 | D | pymongo.serverSelection | {"message": "Server selection succeeded", "selector": "Primary()", "operation": "aggregate", "topologyDescription": "<TopologyDescription id: 666aced542533387f04e44dd, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Standalone, rtt: 0.01600000000325963>]>", "clientId": {"$oid": "666aced542533387f04e44dd"}, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:20:02,743 | D | pymongo.command | {"clientId": {"$oid": "666aced542533387f04e44dd"}, "message": "Command started", "command": "{\"aggregate\": \"user\", \"pipeline\": [{\"$match\": {\"branchId\": {\"$oid\": \"66681d79a3c4ba4888ad4965\"}}}, {\"$group\": {\"totalEmployees\": {\"$sum\": 1}}}, {\"$project\": {\"totalEmployees\": 1}}], \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"wmpGIt1nQ8itVFU2U1NolA==\", \"subType\": \"04\"}}}, \"$db\": \"OfficeDataBase\"}", "commandName": "aggregate", "databaseName": "OfficeDataBase", "requestId": 6334, "operationId": 6334, "driverConnectionId": 1, "serverConnectionId": 87, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:20:02,744 | D | pymongo.command | {"clientId": {"$oid": "666aced542533387f04e44dd"}, "message": "Command succeeded", "durationMS": 1.003, "reply": "{\"cursor\": {\"firstBatch\": [{\"totalEmployees\": 2}], \"ns\": \"OfficeDataBase.user\"}, \"ok\": 1.0}", "commandName": "aggregate", "databaseName": "OfficeDataBase", "requestId": 6334, "operationId": 6334, "driverConnectionId": 1, "serverConnectionId": 87, "serverHost": "127.0.0.1", "serverPort": 27017}
| 2024:06:13 16:20:02,744 | I | STDOUT | {'totalEmployees': 2, 'totalHRs': 0, 'totalClients': 0, 'deliveredProjects': 0, 'pendingProjects': 0, 'totalProjects': 0}
| 2024:06:13 16:20:02,755 | D | root | web\branchManager\dashboard.py 157 get RSP	{'code': 4100, 'status': False, 'message': '', 'result': {'totalEmployees': 2, 'totalHRs': 0, 'totalClients': 0, 'deliveredProjects': 0, 'pendingProjects': 0, 'totalProjects': 0}}
| 2024:06:13 16:20:02,756 | I | tornado.access | 200 GET /v1/api/api/branch/dashboard (::1) 22.18ms
